### PR TITLE
Adding amount to ASSET.

### PR DESCRIPTION
**Pull request by lior-stark**
Renaming NFT_ASSET to ASSET

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starkex-apps-api/6)

### CODE REVIEW

**Review by Yael-Starkware — COMMENTED** [review]
some of the NFT fields should be optional for ERC20 assets. such as collection id

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starkex-apps-api/6#-:-NGv8KW6AYdRHuHId6Z7:byvwwfm)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @AnatVe)

**Review by lior-stark — COMMENTED** [review]
as it currently stands, all properties are optional for "ASSET" (note there's no `required` attribute in the schema)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starkex-apps-api/6#-:-NGvyjaw9mKKXTOXQwPH:b-or1ueg)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @AnatVe)

**Review by Yael-Starkware — COMMENTED** [review]
Should we somehow emphasize which one is for NFT and which for ERC20?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starkex-apps-api/6#-:-NGz8hu77U_Yd9xdzCez:b-m3vm96)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @AnatVe)

**Review by lior-stark — COMMENTED** [review]
originally this was for NFTs, so the collection has a `type` attribute.
we can add a type attribute to the asset, with some predefined types.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starkex-apps-api/6#-:-NGzTs4o3NXLxQVRBvEG:bk6ngr7)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @AnatVe)

**Review by AnatVe — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starkex-apps-api/6#-:-NGzt38T5hcZLxKwTkSC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lior-stark)

**Review by AnatVe — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starkex-apps-api/6#-:-NGztsmJ4F6eKE3gVl6T:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lior-stark)

**Comment by mrjjmc** [comment]
when strk token ?

**Pull request merged**
