### PR TITLE
Extending filters for assets

### PR DESCRIPTION
**Pull request by lior-stark**
Adding the option to filter by collection id and contract address.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starkex-apps-api/1)

### CODE REVIEW

**Review by AnatVe — COMMENTED** [review]
I wanted to add to the API the option to get list of all assets + their mint and transaction history according to collection id/ contract address. 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starkex-apps-api/1#-:-NCKtyWr22Y8OmOjATLT:b-mfbun4)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @lior-stark)

**Review by lior-stark — COMMENTED** [review]
you're saying it's not simply a different filter option?
is the information returned from `getAssetsByFilter` not enough?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starkex-apps-api/1#-:-NCORHhM6Ly_vmSnLSbZ:b-wguunj)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @lior-stark)

**Review by AnatVe — APPROVED** [review]

**Review by AnatVe — APPROVED** [review]

**Review by lior-stark — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starkex-apps-api/1#-:-NCPV1KU21hno0NGHx8j:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @lior-stark)

**Review by AnatVe — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starkex-apps-api/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lior-stark)

**Review by AnatVe — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starkex-apps-api/1#-:-NCTj9JmAqssGqkOv8pF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lior-stark)

**Review by AnatVe — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starkex-apps-api/1#-:-NCTjBjmBw209Jn5EZcO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lior-stark)

**Pull request merged**
